# Generated by Django 4.2.8 on 2024-01-08 03:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=1)),
                ('subject', models.CharField(max_length=2000)),
                ('book_add_time', models.TimeField(default=datetime.datetime(2024, 1, 8, 3, 49, 28, 569503, tzinfo=datetime.timezone.utc))),
                ('book_add_date', models.DateField(default=datetime.date(2024, 1, 8))),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pinjam', models.DateField(default=datetime.date(2024, 1, 8))),
                ('tgl_kembali', models.DateField(blank=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
