# Generated by Django 4.2.8 on 2024-01-08 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 8, 8, 56, 26, 76684, tzinfo=datetime.timezone.utc)),
        ),
    ]
